#include <tf2attributes> // required for weapons module

#include "ilib/objects/rocket.inc"
#include "ilib/objects/particle.inc"
#include "ilib/objects/weapon.inc"
#include "ilib/objects/projlauncher.inc"

#if defined _ilib_objects_included
 #endinput
#endif
#define _ilib_objects_included

/*
* A set of optional headers that contain convenient structs for different entity types.
* None of this is required for ilib to function and is purely optional.
* This header serves mostly as a collection of each entity type and does not hold any native functions.
*/